# Generated by Django 4.0.6 on 2022-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('continuous', models.BooleanField()),
                ('supported_region_min', models.BigIntegerField(blank=True, default=9223372036854775807)),
                ('supported_region_max', models.BigIntegerField(blank=True, default=-9223372036854775808)),
                ('required_variable_count', models.IntegerField(default=0)),
                ('required_variable_names', models.JSONField(blank=True)),
            ],
        ),
    ]
