# Generated by Django 4.0.5 on 2022-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('supported_region', models.CharField(max_length=20)),
                ('param', models.CharField(max_length=100)),
            ],
        ),
    ]
