# Generated by Django 4.0.6 on 2022-07-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statVisualiser', '0002_alter_distribution_supported_region_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='supported_region_max',
            field=models.BigIntegerField(blank=True, default=100000),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='supported_region_min',
            field=models.BigIntegerField(blank=True, default=-100000),
        ),
    ]
