# Generated by Django 4.0.6 on 2022-07-15 07:46

from django.db import migrations, models
import statVisualiser.models


class Migration(migrations.Migration):

    dependencies = [
        ('statVisualiser', '0003_remove_distribution_supportedregion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='requiredVariableNames',
            field=models.JSONField(blank=True, default=statVisualiser.models.Distribution.get_empty),
        ),
    ]
