# Generated by Django 4.0.6 on 2022-07-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statVisualiser', '0003_alter_distribution_supported_region_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='supported_region_max',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='supported_region_min',
        ),
    ]
