# Generated by Django 4.0.6 on 2022-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statVisualiser', '0004_remove_distribution_supported_region_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='supported_region',
            field=models.CharField(default='(∞,∞)', max_length=10),
        ),
    ]
