# Generated by Django 4.0.6 on 2022-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statVisualiser', '0007_alter_distribution_supported_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='supported_region',
            field=models.TextField(default='( ∞ , ∞ )', max_length=50),
        ),
    ]
